[package]
name = "fcut-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
postgres = "0.19.4"
rand = "0.8.5"

[dependencies.redis]
version = "*"
features = ["tokio-comp"] 
